version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-bot}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-botpass}
      POSTGRES_DB: ${POSTGRES_DB:-botdb}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build: ./backend
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  worker:
    build: ./backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./backend/app:/app/app
    command: python -m app.services.engine
    restart: unless-stopped

  web_dashboard:
    build:
      context: ./web_dashboard
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data:
